name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm publish --registry=https://npm.pkg.github.com/@maelgangloff
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
